export const RECEIVE_FIRSTVIEW = "receive_firstview"
export const RECEIVE_CLOTHES = "receive_clothes"
export const RECEIVE_FOODS = "receive_foods"
export const RECEIVE_HEALTH = "receive_health"
export const RECEIVE_TOYS = "receive_toys"